In [3]:
import numpy as np

# Initialize data
X = np.zeros((5, 5, 5))
X[:, :, 0] = np.array([
    [0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 1, 1, 0]
])
X[:, :, 1] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1]
])
X[:, :, 2] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 0]
])
X[:, :, 3] = np.array([
    [0, 0, 0, 1, 0],
    [0, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 1, 0]
])
X[:, :, 4] = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 0]
])

D = np.eye(5)

# Initialize weights
np.random.seed(3)  # For reproducibility
W1 = 2 * np.random.rand(50, 25) - 1
W2 = 2 * np.random.rand(5, 50) - 1
alpha = 0.9

# Train the network
L, M, N = X.shape

for t in range(10000):
    for k in range(N):
        x = X[:, :, k].reshape(25, 1)
        d = D[k, :].reshape(5, 1)
        v1 = np.dot(W1, x)
        y1 = 1 / (1 + np.exp(-v1))
        v = np.dot(W2, y1)
        ex = np.exp(v)
        y = ex / np.sum(ex)
        e = d - y
        delta = e
        e1 = np.dot(W2.T, delta)
        delta1 = y1 * (1 - y1) * e1
        dW1 = alpha * np.dot(delta1, x.T)
        W1 += dW1
        dW2 = alpha * np.dot(delta, y1.T)
        W2 += dW2

# Inference on original data
for k in range(N):
    x = X[:, :, k].reshape(25, 1)
    v1 = np.dot(W1, x)
    y1 = 1 / (1 + np.exp(-v1))
    v = np.dot(W2, y1)
    ex = np.exp(v)
    y = ex / np.sum(ex)
    print(y)

# Contaminated inputs
X_contaminated = np.zeros((5, 5, 6))
X_contaminated[:, :, 0] = np.array([
    [0, 0, 1, 1, 0],
    [0, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 1, 0]
])
X_contaminated[:, :, 1] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
])
X_contaminated[:, :, 2] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 0]
])
X_contaminated[:, :, 3] = np.array([
    [0, 1, 1, 1, 0],
    [0, 1, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 1, 0]
])
X_contaminated[:, :, 4] = np.array([
    [0, 1, 1, 1, 1],
    [0, 1, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0],
    [1, 1, 1, 1, 0]
])
X_contaminated[:, :, 5] = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1]
])
print()
L, M, N = X_contaminated.shape
for k in range(N):
    x = X_contaminated[:, :, k].reshape(25, 1)
    v1 = np.dot(W1, x)
    y1 = 1 / (1 + np.exp(-v1))
    v = np.dot(W2, y1)
    ex = np.exp(v)
    y = ex / np.sum(ex)
    print(y)


[[9.99990560e-01]
 [3.73975045e-06]
 [7.29323123e-07]
 [4.95516529e-06]
 [1.56459758e-08]]
[[3.81399150e-06]
 [9.99984069e-01]
 [1.07138749e-05]
 [7.38201374e-07]
 [6.65377695e-07]]
[[2.10669179e-06]
 [9.17015598e-06]
 [9.99972467e-01]
 [2.22084036e-06]
 [1.40352894e-05]]
[[4.72578106e-06]
 [8.98916172e-07]
 [9.07090140e-07]
 [9.99990801e-01]
 [2.66714208e-06]]
[[6.12205780e-07]
 [2.29663674e-06]
 [1.16748707e-05]
 [1.01696314e-06]
 [9.99984399e-01]]

[[0.57125261]
 [0.03196765]
 [0.0142382 ]
 [0.38164439]
 [0.00089714]]
[[7.83495293e-05]
 [9.86328011e-01]
 [1.34265075e-02]
 [8.02600069e-05]
 [8.68715517e-05]]
[[1.48634814e-04]
 [1.85359520e-02]
 [9.80814029e-01]
 [2.18836701e-04]
 [2.82547314e-04]]
[[1.34825101e-01]
 [7.31477382e-01]
 [1.16776516e-01]
 [1.63681888e-02]
 [5.52812529e-04]]
[[0.0250923 ]
 [0.82517875]
 [0.02682288]
 [0.00243759]
 [0.12046848]]
[[2.17762673e-02]
 [9.77757050e-01]
 [2.27413753e-05]
 [5.80339053e-05]
 [3.85907855e-04]]


In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Initialize data
X = np.zeros((5, 5, 5))
X[:, :, 0] = np.array([
    [0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 1, 1, 0]
])
X[:, :, 1] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1]
])
X[:, :, 2] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 0]
])
X[:, :, 3] = np.array([
    [0, 0, 0, 1, 0],
    [0, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 1, 0]
])
X[:, :, 4] = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 1, 1, 1, 0]
])

D = np.eye(5)

# Reshape X to (num_samples, height, width, channels)
X = X.reshape((5, 5, 5, 1))

# Convert target data to categorical
D = to_categorical(np.arange(5))

# Create the model
model = Sequential([
    Flatten(input_shape=(5, 5, 1)),
    Dense(50, activation='sigmoid'),
    Dense(5, activation='softmax')
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.9),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(X, D, epochs=1000, verbose=0)

# Inference on the original data
print("Inference on original data:")
predictions = model.predict(X)
print(predictions)

# Contaminated inputs
X_contaminated = np.zeros((5, 5, 6))
X_contaminated[:, :, 0] = np.array([
    [0, 0, 1, 1, 0],
    [0, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 1, 0]
])
X_contaminated[:, :, 1] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
])
X_contaminated[:, :, 2] = np.array([
    [1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 0]
])
X_contaminated[:, :, 3] = np.array([
    [0, 1, 1, 1, 0],
    [0, 1, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 1, 0]
])
X_contaminated[:, :, 4] = np.array([
    [0, 1, 1, 1, 1],
    [0, 1, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0],
    [1, 1, 1, 1, 0]
])
X_contaminated[:, :, 5] = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1]
])

# Reshape contaminated X to (num_samples, height, width, channels)
X_contaminated = X_contaminated.reshape((6, 5, 5, 1))

# Inference on contaminated data
print("Inference on contaminated data:")
predictions_contaminated = model.predict(X_contaminated)
print(predictions_contaminated)


Inference on original data:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[9.9831069e-01 6.6604985e-06 4.0982617e-04 3.6202083e-04 9.1075047e-04]
 [5.1803943e-07 9.9897027e-01 2.2916867e-04 4.3453477e-04 3.6545240e-04]
 [4.6576918e-04 1.8976143e-04 9.9904031e-01 8.8981389e-05 2.1512754e-04]
 [3.3753531e-04 4.6724689e-04 6.1401319e-05 9.9913329e-01 5.9443505e-07]
 [8.6036010e-04 3.6000219e-04 2.2632930e-04 8.6389418e-06 9.9854469e-01]]
Inference on contaminated data:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[1.0981539e-03 5.4355770e-02 1.8410454e-02 2.5995031e-02 9.0014058e-01]
 [1.7992668e-02 6.9823787e-02 5.0128061e-02 4.4111267e-01 4.2094278e-01]
 [8.4993339e-01 1.0384440e-03 7.2046719e-03 1.3833188e-01 3.4916108e-03]
 [6.5454221e-01 1.3103228e-02 1.7636141e-02 5.6035090e-02 2.5868335e-01]
 [4.0422538e-03 3.9498204e-01 1.4948025e-01 2.7994412e-01 1.7155127e-01]
 [9.3622375e-01 1.6520690e-04 3.0810698e-03 3.8584203e-02 2.1945812e-02]]
